### PR TITLE
Conditionally add GHC-specific features

### PR DESCRIPTION
**Pull request by RyanGlScott**
The topic of GHC-specific extensions was brought up in #6, but it wasn't really pursued. This pull request attempts to do just that: if a recent-enough version of GHC is being used, the following features are enabled:
- On GHC 7.2 or later, the `Data.Functor.Invariant.Generic` module exports a `genericInvmap` function (requires `FlexibleContexts`). Otherwise, `Data.Functor.Invariant.Generic` exports nothing.
- On GHC 7.6 or later, `PolyKinds` is enabled, making the `Invariant (Tagged s)` instance poly-kinded.

### CODE REVIEW

**Comment by nfrisby** [comment]
LGTM. As always: sorry it took me so long to have a look.

**Comment by nfrisby** [comment]
Do you want to additionally do the `-XDefaultSignatures`, CPP-guarded?

**Comment by RyanGlScott** [comment]
That's a good idea. The only downside is that GHC generics isn't powerful enough to handle some data types like `newtype Fun a b = Fun (a -> b)`, since there's no way for generics to "tunnel into" a function signature like the Template Haskell deriver can. This probably isn't a big deal, though, since `-XDefaultSignatures` would cover a good chunk of data types in the wild.

**Comment by RyanGlScott** [comment]
Also, I'd have to move the definition of `genericInvmap` to `Data.Functor.Invariant` to avoid an import cycle (`.hs-boot` files are scary, man), but that's also a simple change.

**Comment by nfrisby** [comment]
I agree with everything you said.

**Pull request merged**
